# Generated by Django 4.1.7 on 2026-02-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('criticality', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='AssetVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=20, unique=True)),
                ('epss_score', models.FloatField(blank=True, null=True)),
                ('assets', models.ManyToManyField(through='risk.AssetVulnerability', to='risk.asset')),
            ],
        ),
        migrations.AddField(
            model_name='assetvulnerability',
            name='vuln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.vulnerability'),
        ),
        migrations.CreateModel(
            name='AssetDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='risk.asset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='risk.asset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assetvulnerability',
            unique_together={('asset', 'vuln')},
        ),
    ]
