# Generated by Django 4.1.7 on 2026-02-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialModel',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('UEI', models.TextField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('duration', models.TextField()),
                ('main_cause', models.TextField()),
                ('location', models.TextField()),
                ('districts', models.TextField()),
                ('state', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('saverity', models.TextField()),
                ('Area_Affected', models.TextField()),
                ('Human_fatality', models.TextField()),
                ('event_source', models.TextField()),
                ('event_id', models.TextField()),
                ('user_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_url', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'spatial_Details',
            },
        ),
        migrations.CreateModel(
            name='PredictModel',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('UEI', models.TextField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('duration', models.TextField()),
                ('main_cause', models.TextField()),
                ('location', models.TextField()),
                ('districts', models.TextField()),
                ('state', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('saverity', models.TextField()),
                ('Area_Affected', models.TextField()),
                ('Human_fatality', models.TextField()),
                ('event_source', models.TextField()),
                ('event_id', models.TextField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_url_id', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'predict_Details',
            },
        ),
    ]
