# Generated by Django 4.1.7 on 2026-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=100)),
                ('user_dob', models.DateField(max_length=20, null=True)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_occupation', models.TextField(null=True)),
                ('user_image', models.ImageField(upload_to='user/images')),
                ('user_status', models.CharField(default='pending', help_text='user_status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
