# Generated by Django 4.1.7 on 2026-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_set', models.FileField(upload_to='files/')),
                ('dt_Accuracy', models.FloatField(null=True)),
                ('dt_Precision', models.FloatField(null=True)),
                ('dt_Recall', models.FloatField(null=True)),
                ('dt_F1_Score', models.FloatField(null=True)),
                ('dt_algo', models.CharField(default='DecisionTreeClassifier', max_length=50, null=True)),
                ('nb_Accuracy', models.FloatField(null=True)),
                ('nb_Precision', models.FloatField(null=True)),
                ('nb_Recall', models.FloatField(null=True)),
                ('nb_F1_Score', models.FloatField(null=True)),
                ('nb_algo', models.CharField(default='Naive-Bayes', max_length=50, null=True)),
                ('lr_Accuracy', models.FloatField(null=True)),
                ('lr_Precision', models.FloatField(null=True)),
                ('lr_Recall', models.FloatField(null=True)),
                ('lr_F1_Score', models.FloatField(null=True)),
                ('lr_algo', models.CharField(default='Logistic Regression', max_length=50, null=True)),
                ('rf_Accuracy', models.FloatField(null=True)),
                ('rf_Precision', models.FloatField(null=True)),
                ('rf_Recall', models.FloatField(null=True)),
                ('rf_F1_Score', models.FloatField(null=True)),
                ('rf_algo', models.CharField(default='RandomForestClassifier', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
    ]
